name: Build jar

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Gradle
        run: sh ./gradlew build
      - name: Release package
        env:
          USERNAME: netsugo
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sh ./gradlew publish
      - name: Release jar
        uses: softprops/action-gh-release@v1
        with:
          body: ''
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
